import SwiftUI

struct MapView: View {
    @Bindable var store: AppStore
    @State private var showEvidence = true
    var body: some View {
        ZStack(alignment: .bottom) {
            RoomMapCanvas(scan: store.scan).ignoresSafeArea().onTapGesture { showEvidence = true }
            if !showEvidence { LiquidGlassControl { Button { showEvidence = true } label: { Label("Show evidence", systemImage: "line.3.horizontal.decrease.circle").padding(.horizontal, 16).padding(.vertical, 10) } }.padding(.bottom, 32) }
        }.sheet(isPresented: $showEvidence) { MapEvidenceSheet(store: store).presentationDetents([.height(245), .medium, .large]).presentationDragIndicator(.visible).presentationBackgroundInteraction(.enabled(upThrough: .medium)).presentationContentInteraction(.scrolls) }
    }
}

struct RoomMapCanvas: View {
    let scan: RoomScan
    private var labels: [String] { Array((scan.objects.map(\.name) + scan.zones.map(\.name)).prefix(4)) }

    var body: some View { ZStack { LinearGradient(colors: [Color(red: 0.70, green: 0.90, blue: 0.94), Color(red: 0.92, green: 0.95, blue: 0.91)], startPoint: .top, endPoint: .bottom); GeometryReader { _ in Canvas { context, size in for x in stride(from: 0, through: size.width, by: 28) { var p = Path(); p.move(to: CGPoint(x: x, y: 0)); p.addLine(to: CGPoint(x: x, y: size.height)); context.stroke(p, with: .color(.white.opacity(0.3)), lineWidth: 0.6) }; for y in stride(from: 0, through: size.height, by: 28) { var p = Path(); p.move(to: CGPoint(x: 0, y: y)); p.addLine(to: CGPoint(x: size.width, y: y)); context.stroke(p, with: .color(.white.opacity(0.3)), lineWidth: 0.6) } }.overlay { RoundedRectangle(cornerRadius: 26).stroke(OneTheme.accentBlue.opacity(0.45), lineWidth: 2).padding(.horizontal, 42).padding(.vertical, 180).overlay { if labels.isEmpty { Label("No room map yet", systemImage: "map") .font(.headline) .foregroundStyle(OneTheme.secondaryInk) } else { HStack(spacing: 18) { ForEach(Array(labels.enumerated()), id: \.offset) { index, label in RoomMapPin(title: label, color: index.isMultiple(of: 2) ? OneTheme.accentCyan : OneTheme.accentBlue) } }.padding(.horizontal, 48) } } } } }.accessibilityElement(children: .combine).accessibilityLabel(labels.isEmpty ? "No room map available" : "Room map with \(labels.joined(separator: ", "))") } }

struct RoomMapPin: View { let title: String; let color: Color; var body: some View { VStack(spacing: 5) { Circle().fill(color).frame(width: 30, height: 30).overlay(Circle().stroke(.white, lineWidth: 3)).shadow(radius: 6); Text(title).font(.caption.weight(.semibold)).foregroundStyle(OneTheme.ink).padding(.horizontal, 8).padding(.vertical, 4).background(OneTheme.surface, in: Capsule()) } } }

struct MapEvidenceSheet: View { @Bindable var store: AppStore; var body: some View { NavigationStack { ScrollView { VStack(alignment: .leading, spacing: 18) { HStack { VStack(alignment: .leading, spacing: 4) { Text("Home map").font(.largeTitle.weight(.bold)).tracking(-1); Text("Approximate locations · local view").font(.subheadline).foregroundStyle(OneTheme.secondaryInk) }; Spacer(); NavigationLink { ScanView(store: store) } label: { Image(systemName: "viewfinder").font(.title3).frame(width: 44, height: 44) }.buttonStyle(.bordered).accessibilityLabel("Update room scan") }; if store.events.isEmpty { SurfaceCard(radius: 20) { Label("No observations yet", systemImage: "tray").font(.subheadline).foregroundStyle(OneTheme.secondaryInk).padding(16) } } else { LazyVStack(spacing: 0) { ForEach(store.events.prefix(3)) { event in EventRow(event: event); if event.id != store.events.prefix(3).last?.id { Divider() } } } } }.padding(20) }.background(.regularMaterial).navigationBarTitleDisplayMode(.inline) } } }

struct ScanView: View { @Bindable var store: AppStore; @Environment(\.dismiss) private var dismiss; @State private var isCapturing = false; @State private var showCapture = false; var body: some View { ZStack { if showCapture && RoomPlanCapability.isSupported { RoomPlanCaptureView(isCapturing: $isCapturing) { _ in isCapturing = false; showCapture = false; dismiss() }.ignoresSafeArea() } else { VStack(alignment: .leading, spacing: 18) { Text("Refresh the home map").font(.system(size: 36, weight: .bold, design: .rounded)).tracking(-1); if RoomPlanCapability.isSupported { Text("Walk slowly around the room. The scan stays on this device until you choose to share it.").foregroundStyle(OneTheme.secondaryInk); Button { showCapture = true; isCapturing = true } label: { Label("Start LiDAR scan", systemImage: "viewfinder") }.buttonStyle(.borderedProminent).tint(OneTheme.accentBlue).foregroundStyle(.white) } else { Label("LiDAR is not available on this device.", systemImage: "iphone.slash").font(.headline); Text("You can still use ONE with a simple caregiver-created zone map.").foregroundStyle(OneTheme.secondaryInk); Button("Create zones manually") { dismiss() }.buttonStyle(.bordered) }; Spacer() }.padding(24) } }.background(OneTheme.canvas.ignoresSafeArea()).navigationTitle("Room scan").navigationBarTitleDisplayMode(.inline) } }
